# These are supported funding model platforms

# Limited on 4 github-sponsor enabled accounts
github: kreyren

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
# Referer link on github.com/kreyren
custom: https://my.fsf.org/join?referrer=3706032
