name: Bash

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on:
  pull_request:
    types: [ready_for_review]
    paths:
    - 'src/bin/maxx.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - name: Installing dependencies..
        run: |
          # Sync repos
          # Check for git
          if ! apt list --installed 2>/dev/null | grep -qP "^git\/stable.*"; then
            # Check if we can install git
            if ! apt list | grep -qP "^git\/stable.*"; then
              apt update
            elif apt list | grep -qP "^git\/stable.*"; then
              true
            else
              exit 255
            fi
            # Install git
            apt install -y git
          elif apt list --installed 2>/dev/null | grep -qP "^git\/stable.*"; then
            true
          else
            exit 255
          fi
      - name: Pulling git dir..
        uses: actions/checkout@v2
      - name: Building maxx
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE" && make maxx-build
